#!/usr/bin/env python3
"""Regenerate embedded_roms.h from system/amstradcpc/ROM/*.rom.

Run from the SugarLibRetro/ directory after changing the bundled ROM set:

    python3 tools/embed_roms.py

Covers the .rom set plus system.cpr, the Plus/GX4000 system cartridge that
both cartridge-booting models share.
"""
import os
import sys

SRC = 'system/amstradcpc/ROM'
DST = 'embedded_roms.h'

HEADER = """// Generated by tools/embed_roms.py -- do not edit.
//
// The CPC firmware, compiled in so the core works with an empty system
// directory. A real file under <system>/amstradcpc/ROM/ still wins: see
// ApplyEmbeddedRomFallback() in libretro.cpp.
//
// Amstrad have kindly given their permission for the redistribution of
// their copyrighted material but retain that copyright. The bytes below
// are unmodified dumps.

#pragma once
"""


def symbol(name):
    return 'rom_' + name[:-4].replace('.', '_').replace('-', '_')


def main():
    if not os.path.isdir(SRC):
        sys.exit('%s not found -- run this from the SugarLibRetro/ directory' % SRC)

    names = sorted(n for n in os.listdir(SRC)
                   if n.endswith('.rom') or n.endswith('.cpr'))
    if not names:
        sys.exit('no .rom or .cpr files in %s' % SRC)

    out = [HEADER]
    for name in names:
        with open(os.path.join(SRC, name), 'rb') as f:
            data = f.read()
        out.append('static const unsigned char %s[%d] = {' % (symbol(name), len(data)))
        for i in range(0, len(data), 16):
            out.append('   ' + ','.join('0x%02X' % b for b in data[i:i + 16]) + ',')
        out.append('};')
        out.append('')

    out.append('struct EmbeddedRom { const char* name; const unsigned char* data; unsigned int size; };')
    out.append('')
    out.append('static const EmbeddedRom kEmbeddedRoms[] = {')
    for name in names:
        out.append('   { "%s", %s, sizeof(%s) },' % (name, symbol(name), symbol(name)))
    out.append('};')
    out.append('')

    with open(DST, 'w') as f:
        f.write('\n'.join(out) + '\n')
    print('%s: %d images, %d bytes' % (DST, len(names), os.path.getsize(DST)))


if __name__ == '__main__':
    main()
